spring.application.name=minimarket

# Configuracion MySQL
spring.datasource.url=jdbc:mysql://db:3306/minimarket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:minimarket}
spring.datasource.password=${DB_PASSWORD:minimarket}

# Configuracion de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.devtools.restart.enabled=false